language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - echo "Done"
deploy:
  provider: heroku
  api_key:
    secure: eoqWFxs/K56d50Y0QWF8Bne5+obdeFM/lAwSC9z2icAhodrWxjhK7c1lnbJmGLpTV03Kgm6leASRn55WERFIEF8M8y19+OsIHOM+4Tj45ldlk2rB4GaV5QReBdRgwqjpxKcPkHsBiZ23ATse5KlXFqRyYpyswTQDBeGfZ3q6/+7L8Z8bOS9zmb1ZT2J8cGKgRoaqXE5TGzy/qDJZBPN7YkboZBKfgW6jFPxX9AQvrODN1iRgw+EZQDf0IPcJ67/qWewOVA/z3I9hwiYEFoa6dNB6Xd/0PO0yvlx0ms31JRslXe5bEz5Bg/vO8wEAqGKTbUkHzIa8rQs2Sw90GF7dbrm3J5bM6LcuTiWXEdmyALszI69HUCb7XXikQF0o2mrYZe/Sp3Uztp/4PXCbCk3rEatOA65Kox8hzftKKRhzRjPNFCddLLNeMmJ1h41B44dUfh+2VXCVB7rMzxEDQ2yFYeYgMyGa9SDCGzdMzpB9/fIIPnbDgpgGg3ldwMkXVCo5fMW4Xz1okBunrt+JBld4C2X9d607+Rp5tW0wNUWQNSWwjcN2NJlXaqaZXHxRhbKOYLw9hNuox/zW423IsxFurwEY7Imi3IsU4WAkBuc1LewZnFXFPdu9dG+TFZDzcOG93vsxKanoCOuzqPgmJnaDrvgAXbBuDOvoz+RadeksWU4=